In [1]:
import pandas as pd
import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

sns.set_theme(style="whitegrid")

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 50)

DATA_PATH = "bina_az_data_template.xlsx"

OUT_DIR = Path("eda_output")
OUT_DIR.mkdir(exist_ok=True)

print("Setup completed.")

Setup completed.

In [2]:
df = pd.read_excel(
    DATA_PATH,
    sheet_name="Melumatlar"
)

print("Original shape:", df.shape)

df.head()

Original shape: (100, 35)

,sira_no,elan_nomresi,url,elan_novu,emeliyyat_novu,seher,rayon,mikrorayon_kompleks,metro,nishangah,latitude,longitude,otaq_sayi,sahe_m2,torpaq_sahe_sot,mertebe,bina_mertebe_sayi,temir,cixaris_kupca,ipoteka,daxili_kredit,qiymet_azn,qiymet_vahidi,qiymet_m2,satici_novu,kompleks_elanidir,baxis_sayi,yenilenme_tarixi,yelceken,deniz_menzeresi,mebel,qaz_kombi,qaraj,elan_metni,qeydler
0,1,NaN,NaN,Mənzil (yeni tikili),Satış,Bakı,Sabunçu r.,Sea Breeze Palm Beach,NaN,Sea Breeze,NaN,NaN,1.0,NaN,NaN,NaN,7.0,Naməlum,Naməlum,Var,Var,354152.0,AZN,NaN,Tikinti şirkəti,Bəli,NaN,NaN,NaN,1.0,NaN,NaN,NaN,Birinci sahil zolağında yeni tikili kompleks; ...,Konkret mənzil deyil — kompleksin 1 otaqlılar ...
1,2,6196330.0,NaN,Həyət evi/Bağ evi,Kirayə,Qəbələ,Qəbələ rayonu,NaN,NaN,NaN,NaN,NaN,5.0,300.0,8.0,NaN,NaN,Var,Naməlum,Naməlum,Naməlum,300.0,AZN/gün,1.0,Mülkiyyətçi,Xeyr,6543.0,"Bugün, 18:31 (nümunə mətndən — real tarixlə əv...",1.0,0.0,1.0,NaN,0.0,"Qəbələdə dağ mənzərəli, hovuzlu, tam təchizatl...",Günlük kirayə (AZN/gün) — qiymet_m2 nəticəsi s...
2,3,NaN,NaN,Həyət evi/Bağ evi,Satış,Bakı,Naməlum (mətndə: Badamdar ərazisi),3-cü massiv,NaN,NaN,NaN,NaN,8.0,400.0,6.0,NaN,NaN,Var,Var,Naməlum,Naməlum,990000.0,AZN,2475.0,Mülkiyyətçi,Xeyr,NaN,NaN,NaN,0.0,NaN,1.0,0.0,"Yüksək keyfiyyətli materiallarla tikilmiş, gen...","Elanda ""bu qiymətə belə ev yoxdur, ucuz satılı..."
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data_columns = [
    col for col in df.columns
    if col != "sira_no"
]

df = df.dropna(
    how="all",
    subset=data_columns
).copy()

print("Shape after removing completely empty rows:", df.shape)

Shape after removing completely empty rows: (3, 35)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sira_no              3 non-null      int64
 1   elan_nomresi         1 non-null      float64
 2   url                  0 non-null      float64
 3   elan_novu            3 non-null      object
 4   emeliyyat_novu       3 non-null      object
 5   seher                3 non-null      object
 6   rayon                3 non-null      object
 7   mikrorayon_kompleks  2 non-null      object
 8   metro                0 non-null      float64
 9   nishangah            1 non-null      object
 10  latitude             0 non-null      float64
 11  longitude            0 non-null      float64
 12  otaq_sayi            3 non-null      float64
 13  sahe_m2              2 non-null      float64
 14  torpaq_sahe_sot      2 non-null      float64
 15  mertebe              0 non-null      float64
 16  bina_mertebe_sayi    1 non-null      float64
 17  temir                3 non-null      object
 18  cixaris_kupca        3 non-null      object
 19  ipoteka              3 non-null      object
 20  daxili_kredit        3 non-null      object
 21  qiymet_azn           3 non-null      float64
 22  qiymet_vahidi        3 non-null      object
 23  qiymet_m2            2 non-null      float64
 24  satici_novu          3 non-null      object
 25  kompleks_elanidir    3 non-null      object
 26  baxis_sayi           1 non-null      float64
 27  yenilenme_tarixi     1 non-null      object
 28  yelceken             1 non-null      float64
 29  deniz_menzeresi      3 non-null      float64
 30  mebel                1 non-null      float64
 31  qaz_kombi            1 non-null      float64
 32  qaraj                2 non-null      float64
 33  elan_metni           3 non-null      object
 34  qeydler              3 non-null      object
dtypes: float64(18), int64(1), object(16)
memory usage: 864.0+ bytes

In [5]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [6]:
if "elan_nomresi" in df.columns:
    print(
        "Duplicate listing IDs:",
        df["elan_nomresi"].dropna().duplicated().sum()
    )

Duplicate listing IDs: 0

In [7]:
missing = (
    df.isna()
    .mean()
    .mul(100)
    .round(1)
    .sort_values(ascending=False)
)

missing = missing[missing > 0]

print("Missing values (%):")
print(missing)

Missing values (%):
longitude              100.0
url                    100.0
mertebe                100.0
latitude               100.0
metro                  100.0
yenilenme_tarixi        66.7
elan_nomresi            66.7
bina_mertebe_sayi       66.7
baxis_sayi              66.7
nishangah               66.7
mebel                   66.7
qaz_kombi               66.7
yelceken                66.7
mikrorayon_kompleks     33.3
qiymet_m2               33.3
sahe_m2                 33.3
torpaq_sahe_sot         33.3
qaraj                   33.3
dtype: float64

In [8]:
categorical_cols = [
    "elan_novu",
    "emeliyyat_novu",
    "seher",
    "rayon",
    "mikrorayon_kompleks",
    "metro",
    "temir",
    "cixaris_kupca",
    "ipoteka",
    "daxili_kredit",
    "satici_novu",
    "kompleks_elanidir",
    "qiymet_vahidi"
]

for col in categorical_cols:
    if col in df.columns:
        print(f"\n--- {col} ---")
        print(df[col].value_counts(dropna=False))

--- elan_novu ---
elan_novu
Həyət evi/Bağ evi       2
Mənzil (yeni tikili)    1
Name: count, dtype: int64

--- emeliyyat_novu ---
emeliyyat_novu
Satış     2
Kirayə    1
Name: count, dtype: int64

--- seher ---
seher
Bakı      2
Qəbələ    1
Name: count, dtype: int64

--- rayon ---
rayon
Sabunçu r.                            1
Qəbələ rayonu                         1
Naməlum (mətndə: Badamdar ərazisi)    1
Name: count, dtype: int64

--- mikrorayon_kompleks ---
mikrorayon_kompleks
Sea Breeze Palm Beach    1
NaN                      1
3-cü massiv              1
Name: count, dtype: int64

--- metro ---
metro
NaN    3
Name: count, dtype: int64

--- temir ---
temir
Var        2
Naməlum    1
Name: count, dtype: int64

--- cixaris_kupca ---
cixaris_kupca
Naməlum    2
Var        1
Name: count, dtype: int64

--- ipoteka ---
ipoteka
Naməlum    2
Var        1
Name: count, dtype: int64

--- daxili_kredit ---
daxili_kredit
Naməlum    2
Var        1
Name: count, dtype: int64

--- satici_novu ---
satici_novu
Mülkiyyətçi        2
Tikinti şirkəti    1
Name: count, dtype: int64

--- kompleks_elanidir ---
kompleks_elanidir
Xeyr    2
Bəli    1
Name: count, dtype: int64

--- qiymet_vahidi ---
qiymet_vahidi
AZN        2
AZN/gün    1
Name: count, dtype: int64

In [9]:
print(
    df["emeliyyat_novu"]
    .value_counts(dropna=False)
)

emeliyyat_novu
Satış     2
Kirayə    1
Name: count, dtype: int64

In [10]:
n_sales = (
    df["emeliyyat_novu"] == "Satış"
).sum()

n_rent = (
    df["emeliyyat_novu"] == "Kirayə"
).sum()

print("Sales:", n_sales)
print("Rent:", n_rent)

Sales: 2
Rent: 1

In [11]:
print(
    df["kompleks_elanidir"]
    .value_counts(dropna=False)
)

kompleks_elanidir
Xeyr    2
Bəli    1
Name: count, dtype: int64

In [12]:
df_core = df[
    (df["emeliyyat_novu"] == "Satış") &
    (df["kompleks_elanidir"] != "Bəli") &
    (df["qiymet_vahidi"] == "AZN")
].copy()

print("Core dataset shape:", df_core.shape)

Core dataset shape: (1, 35)

In [13]:
numeric_cols = [
    "otaq_sayi",
    "sahe_m2",
    "torpaq_sahe_sot",
    "mertebe",
    "bina_mertebe_sayi",
    "qiymet_azn",
    "qiymet_m2",
    "baxis_sayi"
]

numeric_cols = [
    col for col in numeric_cols
    if col in df_core.columns
]

print(numeric_cols)

['otaq_sayi', 'sahe_m2', 'torpaq_sahe_sot', 'mertebe', 'bina_mertebe_sayi', 'qiymet_azn', 'qiymet_m2', 'baxis_sayi']

In [14]:
if len(df_core) >= 5:
    print(
        df_core[numeric_cols]
        .describe()
        .T
    )
else:
    print(
        f"Only {len(df_core)} core rows available. "
        "Descriptive statistics will be meaningful after more data is added."
    )

Only 1 core rows available. Descriptive statistics will be meaningful after more data is added.

In [15]:
checks = {
    "negative_price": (
        df_core["qiymet_azn"] < 0
    ).sum(),

    "zero_price": (
        df_core["qiymet_azn"] == 0
    ).sum(),

    "negative_area": (
        df_core["sahe_m2"] < 0
    ).sum(),

    "zero_area": (
        df_core["sahe_m2"] == 0
    ).sum(),

    "negative_rooms": (
        df_core["otaq_sayi"] < 0
    ).sum(),

    "zero_rooms": (
        df_core["otaq_sayi"] == 0
    ).sum()
}

pd.Series(checks)

negative_price    0
zero_price        0
negative_area     0
zero_area         0
negative_rooms    0
zero_rooms        0
dtype: int64

In [16]:
invalid_floor = df_core[
    df_core["mertebe"].notna() &
    df_core["bina_mertebe_sayi"].notna() &
    (
        (df_core["mertebe"] <= 0) |
        (df_core["bina_mertebe_sayi"] <= 0) |
        (df_core["mertebe"] > df_core["bina_mertebe_sayi"])
    )
]

print("Invalid floor records:", len(invalid_floor))

Invalid floor records: 0

In [17]:
df["area_per_room"] = (
    df["sahe_m2"] /
    df["otaq_sayi"].replace(0, np.nan)
)

df[
    [
        "sahe_m2",
        "otaq_sayi",
        "area_per_room"
    ]
].head()

   sahe_m2  otaq_sayi  area_per_room
0      NaN        1.0            NaN
1    300.0        5.0           60.0
2    400.0        8.0           50.0

In [18]:
df["floor_ratio"] = (
    df["mertebe"] /
    df["bina_mertebe_sayi"].replace(0, np.nan)
)

df[
    [
        "mertebe",
        "bina_mertebe_sayi",
        "floor_ratio"
    ]
].head()

   mertebe  bina_mertebe_sayi  floor_ratio
0      NaN                7.0          NaN
1      NaN                NaN          NaN
2      NaN                NaN          NaN

In [19]:
df["is_top_floor"] = (
    df["mertebe"].notna() &
    df["bina_mertebe_sayi"].notna() &
    (
        df["mertebe"] ==
        df["bina_mertebe_sayi"]
    )
).astype("int8")

In [20]:
df["is_first_floor"] = (
    df["mertebe"] == 1
).astype("int8")

In [21]:
engineered_features = [
    "area_per_room",
    "floor_ratio",
    "is_top_floor",
    "is_first_floor"
]

df[
    engineered_features
].head(10)

   area_per_room  floor_ratio  is_top_floor  is_first_floor
0            NaN          NaN             0               0
1           60.0          NaN             0               0
2           50.0          NaN             0               0

In [22]:
df[engineered_features].describe()

       area_per_room  floor_ratio  is_top_floor  is_first_floor
count       2.000000          0.0           3.0             3.0
mean       55.000000          NaN           0.0             0.0
std         7.071068          NaN           0.0             0.0
min        50.000000          NaN           0.0             0.0
25%        52.500000          NaN           0.0             0.0
50%        55.000000          NaN           0.0             0.0
75%        57.500000          NaN           0.0             0.0
max        60.000000          NaN           0.0             0.0

In [23]:
selected_features = [
    "elan_novu",
    "seher",
    "rayon",
    "mikrorayon_kompleks",
    "metro",
    "nishangah",
    "otaq_sayi",
    "sahe_m2",
    "torpaq_sahe_sot",
    "mertebe",
    "bina_mertebe_sayi",
    "temir",
    "cixaris_kupca",
    "ipoteka",
    "daxili_kredit",
    "satici_novu",
    "baxis_sayi",
    "area_per_room",
    "floor_ratio",
    "is_top_floor",
    "is_first_floor"
]

selected_features = [
    col for col in selected_features
    if col in df.columns
]

print("Selected features:")
print(selected_features)

Selected features:
['elan_novu', 'seher', 'rayon', 'mikrorayon_kompleks', 'metro', 'nishangah', 'otaq_sayi', 'sahe_m2', 'torpaq_sahe_sot', 'mertebe', 'bina_mertebe_sayi', 'temir', 'cixaris_kupca', 'ipoteka', 'daxili_kredit', 'satici_novu', 'baxis_sayi', 'area_per_room', 'floor_ratio', 'is_top_floor', 'is_first_floor']

In [24]:
valid_price_m2 = df_core[
    "qiymet_m2"
].dropna()

print(
    "Valid price/m² values:",
    len(valid_price_m2)
)

Valid price/m² values: 1

In [25]:
if len(valid_price_m2) >= 5:

    plt.figure(figsize=(8, 5))

    sns.histplot(
        valid_price_m2,
        bins=20,
        kde=True
    )

    plt.title("Price per m² Distribution")
    plt.xlabel("AZN / m²")
    plt.ylabel("Number of listings")

    plt.tight_layout()

    plt.savefig(
        OUT_DIR / "price_per_m2_distribution.png",
        dpi=150
    )

    plt.close()

    print("Histogram saved.")

else:

    print(
        "Not enough valid price/m² values for visualization yet."
    )

Not enough valid price/m² values for visualization yet.

In [28]:
corr_features = [
    "otaq_sayi",
    "sahe_m2",
    "torpaq_sahe_sot",
    "mertebe",
    "bina_mertebe_sayi",
    "baxis_sayi",
    "area_per_room",
    "floor_ratio",
    "is_top_floor",
    "is_first_floor",
    "qiymet_azn"
]

corr_features = [
    col for col in corr_features
    if col in df_core.columns or col in df.columns
]

In [29]:
analysis_df = df_core.copy()

for col in [
    "area_per_room",
    "floor_ratio",
    "is_top_floor",
    "is_first_floor"
]:
    analysis_df[col] = df.loc[
        analysis_df.index,
        col
    ]

In [30]:
if len(analysis_df) >= 5:

    corr = analysis_df[
        corr_features
    ].corr(numeric_only=True)

    plt.figure(figsize=(10, 8))

    sns.heatmap(
        corr,
        annot=True,
        fmt=".2f",
        center=0
    )

    plt.title(
        "Correlation Between Numerical Features"
    )

    plt.tight_layout()

    plt.savefig(
        OUT_DIR / "correlation_heatmap.png",
        dpi=150
    )

    plt.close()

    print("Correlation heatmap saved.")

else:

    print(
        "Not enough data for meaningful correlation analysis yet."
    )

Not enough data for meaningful correlation analysis yet.

In [31]:
if len(valid_price_m2) >= 5:

    q1 = valid_price_m2.quantile(0.25)
    q3 = valid_price_m2.quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df_core[
        (df_core["qiymet_m2"] < lower_bound) |
        (df_core["qiymet_m2"] > upper_bound)
    ]

    print(
        f"Lower bound: {lower_bound:.2f}"
    )

    print(
        f"Upper bound: {upper_bound:.2f}"
    )

    print(
        "Number of outliers:",
        len(outliers)
    )

else:

    print(
        "Not enough data for reliable outlier detection yet."
    )

Not enough data for reliable outlier detection yet.

In [32]:
final_columns = [
    "elan_novu",
    "seher",
    "rayon",
    "mikrorayon_kompleks",
    "metro",
    "nishangah",
    "otaq_sayi",
    "sahe_m2",
    "torpaq_sahe_sot",
    "mertebe",
    "bina_mertebe_sayi",
    "temir",
    "cixaris_kupca",
    "ipoteka",
    "daxili_kredit",
    "satici_novu",
    "baxis_sayi",
    "area_per_room",
    "floor_ratio",
    "is_top_floor",
    "is_first_floor",
    "qiymet_azn"
]

final_columns = [
    col for col in final_columns
    if col in df.columns
]

df_final = df[
    final_columns
].copy()

print("Final dataset shape:", df_final.shape)

df_final.head()

Final dataset shape: (3, 22)

,elan_novu,seher,rayon,mikrorayon_kompleks,metro,nishangah,otaq_sayi,sahe_m2,torpaq_sahe_sot,mertebe,bina_mertebe_sayi,temir,cixaris_kupca,ipoteka,daxili_kredit,satici_novu,baxis_sayi,area_per_room,floor_ratio,is_top_floor,is_first_floor,qiymet_azn
0,Mənzil (yeni tikili),Bakı,Sabunçu r.,Sea Breeze Palm Beach,NaN,Sea Breeze,1.0,NaN,NaN,NaN,7.0,Naməlum,Naməlum,Var,Var,Tikinti şirkəti,NaN,NaN,NaN,0,0,354152.0
1,Həyət evi/Bağ evi,Qəbələ,Qəbələ rayonu,NaN,NaN,NaN,5.0,300.0,8.0,NaN,NaN,Var,Naməlum,Naməlum,Naməlum,Mülkiyyətçi,6543.0,60.0,NaN,0,0,300.0
2,Həyət evi/Bağ evi,Bakı,Naməlum (mətndə: Badamdar ərazisi),3-cü massiv,NaN,NaN,8.0,400.0,6.0,NaN,NaN,Var,Var,Naməlum,Naməlum,Mülkiyyətçi,NaN,50.0,NaN,0,0,990000.0

In [33]:
TARGET = "qiymet_azn"

FEATURES = [
    col for col in df_final.columns
    if col != TARGET
]

print("TARGET:")
print(TARGET)

print("\nFEATURES:")
print(FEATURES)

TARGET:
qiymet_azn

FEATURES:
['elan_novu', 'seher', 'rayon', 'mikrorayon_kompleks', 'metro', 'nishangah', 'otaq_sayi', 'sahe_m2', 'torpaq_sahe_sot', 'mertebe', 'bina_mertebe_sayi', 'temir', 'cixaris_kupca', 'ipoteka', 'daxili_kredit', 'satici_novu', 'baxis_sayi', 'area_per_room', 'floor_ratio', 'is_top_floor', 'is_first_floor']

In [34]:
final_missing = (
    df_final.isna()
    .mean()
    .mul(100)
    .round(1)
    .sort_values(ascending=False)
)

print("Missing values in final dataset (%):")
print(
    final_missing[
        final_missing > 0
    ]
)

Missing values in final dataset (%):
metro                  100.0
mertebe                100.0
floor_ratio            100.0
nishangah               66.7
bina_mertebe_sayi       66.7
baxis_sayi              66.7
mikrorayon_kompleks     33.3
sahe_m2                 33.3
torpaq_sahe_sot         33.3
area_per_room           33.3
dtype: float64

In [35]:
OUTPUT_PATH = "bina_az_cleaned_features.csv"

df_final.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(
    f"Saved: {OUTPUT_PATH}"
)

Saved: bina_az_cleaned_features.csv